apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-sm-cluster-secret-store
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-sa-secret
            namespace: infra-secrets
            key: secret-access-credentials
      projectID: {{ .Values.gcp.projectID }}
